Add purpur afk support
TheJeterLP/ChatEx pull request #64
Opened 2022-07-29 07:46 UTC by DreamVoid

To enable purpur afk, change `player-idle-time` in `server.properties` and  change `kick-if-idle` to `false` in `purpur.yml`.

Tested in my server.

2022-07-29 09:32 UTC, TheJeterLP commented
What is purpur afk?

2022-07-29 09:34 UTC, TheJeterLP requested changes

2022-07-29 09:34 UTC, TheJeterLP commented on src/main/java/de/jeter/chatex/utils/Utils.java
> +            result = result.replace("%afk", "");
That's dupe code here, please include that if to the upper if which checks for essentials already

2022-07-29 10:44 UTC, DreamVoid commented
> What is purpur afk?

Purpur is a Paper and Pufferfish fork. It override vanilla idle timeout and provided an api. Here's its document: https://purpurmc.org/docs/Configuration/#idle-timeout

2022-08-07 06:02 UTC, TheJeterLP approved these changes

2022-08-07 06:03 UTC, merged